spring:
  profiles:
    active: local

# for DB Connection
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${SWINGHEIL_DB_CONNECTION_STRING}
    username: ${SWINGHEIL_DB_USERNAME}
    password: ${SWINGHEIL_DB_PASSWORD}

# for JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
          show_sql: false
          format_sql: true
          use_sql_comments: false

# for Encoding UTF-8
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

# for logging
logging:
  level:
    jdbc:
      sqlonly: FATAL
      audit: FATAL
      connection: FATAL
      resultset: FATAL

## LOCAL ENVIRONMENT
---
spring:
  profiles: local

  datasource:
    url: jdbc:log4jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    properties:
      hibernate:
          show_sql: true


## DEVELOPMENT ENVIRONMENT
---
spring:
  profiles: dev


## PRODUCTION ENVIRONMENT
---
spring:
  profiles: prd

  jpa:
    hibernate:
      ddl-auto: validate

  devtools:
    livereload:
      enabled: false